### ISSUE TITLE
Hanukkah is not shown on December 31st, 2024

### ISSUE THREAD

**Issue by roniger** [py-libhdate/py-libhdate#133]
# Observed behavior
<img width="465" alt="image" src="https://github.com/user-attachments/assets/3898c24d-38f7-4e96-adbe-c41f5ec65ae1">
31-12-2024 should be marked as Hanukkah, but is returned as False

# Expected behavior
<img width="453" alt="image" src="https://github.com/user-attachments/assets/55f3711e-4e0d-49c5-8277-7f7c478f42e9">

# Steps to reproduce
`
from hdate import HDate
from datetime import datetime

date = HDate(datetime(2024, 12, 31), hebrew=True)
print(date.hebrew_date)
print(date.is_holiday)
`

**Comment by tsvi** [comment]
Thank you very much for the report.

Could you add the following information?
a. What version are you using?
b. Could you check the result for `date._holiday_entries()`

**Comment by roniger** [comment]
Hi,
Thank you!
I am using version 0.10.11.
This is the holiday entries output: []

**Comment by tsvi** [comment]
Thank you, managed to reproduce the bug and fix it.
Will release an updated version in the upcoming week.,

**Comment by roniger** [comment]
Thank you very much! Great news
