### ISSUE TITLE
is_holiday returns True for dates with no holidays

### ISSUE THREAD

**Issue by roniger** [py-libhdate/py-libhdate#137]
# Observed behavior
In version 0.11.0 there is regression, where is_holiday is returned True for every date.

When initiating HDate it should return True for is_holiday only for dates of holidays.
For example: for date 2025-07-06 it returns true, but _holiday_entires() returns an empty array

# Expected behavior
Return false when there is no holiday

# Steps to reproduce
'''
from hdate import HDate
from hdate.htables import HOLIDAY
from datetime import datetime

date = HDate(datetime(2025, 7, 6), hebrew=True)
print(date.hebrew_date)
print(date.is_holiday)
print(date._holiday_entries())

output:
י' תמוז ה' תשפ"ה
True
[]
'''

**Comment by tsvi** [comment]
Thank you for the report, will add a test for that
