### ISSUE TITLE
List all the shabbatot in year

### ISSUE THREAD

**Issue by eyammer** [py-libhdate/py-libhdate#93]
# Feature description
I would like to be able to list the date of every shabbat in a given Jewish year. 
Perhaps this could be done by adding a shabbat type in the holiday type list.

**Comment by yuvalabou** [comment]
Why is it useful?

**Comment by DanBendavid** [comment]
You can do it easily from Jupiter notebook

import hdate
import datetime
import random
from calendar import isleap
from hdate.htables import HolidayTypes, Months
from hdate.date import HDate, get_omer_string, hebrew_number
from hdate import converters as conv
from hdate.hebrew_date import HebrewDate


import pandas as pd
from datetime import timedelta
c = hdate.Location("Paris", 48.854442, 2.277626, "Europe/Paris", 35, True)
rdate_start = datetime.date(2023, 10, 22)
jdate_start = conv.gdate_to_jdn(rdate_start)
for x in range(104):
  
  jdate = jdate_start + x*7
  gdate = conv.jdn_to_gdate (jdate)
  print(gdate)  
  
  
  h = hdate.HDate(gdate, diaspora=True, lang='french')
  if h.is_holiday:
      print("Holiday")
  parasha = h.parasha
  print(parasha)  
  h = hdate.HDate(gdate, diaspora=True, lang='english')
  parasha = h.parasha
  print(parasha)  
  h = hdate.HDate(gdate, diaspora=True, lang='hebrew')
  parasha = h.parasha
  print(parasha)

**Comment by tsvi** [comment]
I'm sorry but shabbat is always on Saturday.
I don't think adding this functionality to py-libhdate is useful.

```python
from datetime import date, timedelta

from hdate import HDate, HebrewDate

def get_shabatot_in_year(year):
    """Return a list of all Shabatot."""
    rosh_hashana = HDate(HebrewDate(1, 1, year)).gdate
    next_rosh_hashana = HDate(HebrewDate(1, 1, year + 1)).gdate

    # Find the first Shabbat on or after rosh_hashana
    current_date = rosh_hashana
    while current_date.weekday() != 5:  # 5 corresponds to Saturday
        current_date += timedelta(days=1)

    number_of_shabatot = (next_rosh_hashana - current_date).days // 7 + 1
    shabatot = [current_date + timedelta(days=7 * i) for i in range(number_of_shabatot)]
    return shabatot

# Example usage:
shabatot = get_shabatot_in_year(5785)
print(shabatot)
```
