### ISSUE TITLE
motzei_shabbat_chag should be true when now() == havdalah time

### ISSUE THREAD

**Issue by amitfin** [py-libhdate/py-libhdate#97]
The bug is [here](https://github.com/py-libhdate/py-libhdate/blob/0e09a55df4c337056bcf36077e59aad764d2813c/hdate/zmanim.py#L241):
```
if (today.is_shabbat or today.is_yom_tov) and (self.time > self.havdalah):
```
And it should be:
```
if (today.is_shabbat or today.is_yom_tov) and (self.time >= self.havdalah):
```

The problem is with Home Assistant integration. We evaluate the binary sensor only at the moment of ```havdalah``` (see [here](https://github.com/home-assistant/core/blob/1acb9a981a5c7b9a012d6b18bad581fb84ac54c7/homeassistant/components/jewish_calendar/binary_sensor.py#L134)). However, with the current implementation ```motzei_shabbat_chag``` stays ```False``` at that moment. We never update the sensor again on that day.

(This is a similar issue as the one fixed by https://github.com/py-libhdate/py-libhdate/pull/78)

**Comment by tsvi** [comment]
Thanks @amitfin for this finding
